"""auto-vote

Revision ID: 121969b58a84
Revises: 10d55d0effad
Create Date: 2022-10-07 15:20:30.502558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121969b58a84'
down_revision = '10d55d0effad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('users', sa.Column('fullname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'username')
    op.drop_column('users', 'fullname')
    op.drop_table('votes')
    # ### end Alembic commands ###
